# Generated by Django 3.2 on 2022-02-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentsapp', '0002_auto_20220228_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Occupied'), (2, 'Pending')], default=0),
        ),
    ]
